<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\quick-qr.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace>QuickQr</RootNamespace>
    <AssemblyName>QuickQr</AssemblyName>
    <Platforms>AnyCPU</Platforms>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
    <Version>0.0.1</Version>
    <FileVersion>0.0.1.0</FileVersion>
    <InformationalVersion>0.0.1</InformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <None Include="Assets\quick-qr.ico" />
    <Resource Include="Assets\quick-qr.png" />
    <None Include="app.manifest" />
  </ItemGroup>
</Project>
